COMMON_DISPOSITIONS = [
    'Services Rendered',
    'Unit Clear',
    'Transported to Hospital',
    'Unfounded',
    'Report taken',
    'Verbal Warning',
    'Verbal Warning',
    'False Alarm',
    'Citation/Warning Issued',
    'Parking Ticket Issued',
    'Arrest 17 and Over Fem',
    'Restraining Order Served',
    'Building Checked - Secur',
    'Could Not Locate',
    'Vehicle Towed',
    'Arrest 17 and Over Mal',
    'Notification Made',
    'Restraining Order Not Se',
    'Peace Restored',
    'Summons Served',
    'Summons Not Served',
    'No Action Required',
    'Building Checked -Secur',
    'Notified Agency',
    'Prot. Cust. 18 & Over',
    'Taken/Referred to Other',
    'Secured Building',
    'Arrest Under 17 Male',
    'Transported',
    'Taken to Family/Guardian',
    'Field Interrogation',
    'Prot.Cust.18 & Over',
    'Investigated',
    'SummonsServed',
    'UnitClear',
    'NotificationMade',
    'SummonsNot Served',
    'Removed Hazard',
    'PeaceRestored',
    'Prot.Cust. 18 & Over',
]
